### ISSUE TITLE
json to csv convert

### ISSUE THREAD

**Issue by Shrewd8223** [tulasinnd/PhonePe-Pulse-Data-2018-2022-Analysis#1]

**Comment by tulasinnd** [comment]
Our objective is to write a code that can iterate through all directories and subdirectories, extract data from JSON files, and create dataframe rows. Our specific goal is to convert each document in the JSON files into a dataframe row. I have provided a code snippet that outlines the approach


import os
from os import walk
from pathlib import Path
import pandas as pd

def Aggregated_Transaction_Table_fun(state,year,quarter,path):
    global Data_Aggregated_Transaction_Table
    global Data_Aggregated_Transaction_Summary_Table
    dft = pd.read_json(path)
    
    dataFrom=dft['data']['from']
    dataTo=dft['data']['to'] 
    T_row={'State':state,'Year': year,'Quarter':quarter,'Data From':dataFrom,'Data To':dataTo}
    Data_Aggregated_Transaction_Summary_Table=Data_Aggregated_Transaction_Summary_Table.append(T_row,ignore_index = True)
    
    DAT_temp=dft['data']['transactionData']
    if DAT_temp:      
        for i in DAT_temp:
            DAT_row={ 'Payment Mode':i['name'], 'Total Transactions count':i['paymentInstruments'][0]['count'], 'Total Amount':i['paymentInstruments'][0]['amount'],'Quarter':quarter,'Year': year,'State':state}  
            Data_Aggregated_Transaction_Table = Data_Aggregated_Transaction_Table.append(DAT_row, ignore_index = True)
        
t_s= r'C:\Users\91939\2MY_DATA_SCIENCE\12_My_DS_Tasks\project2_Phonepay\data\aggregated\transaction\country\india\state'
t_path = r'C:\Users\91939\2MY_DATA_SCIENCE\12_My_DS_Tasks\project2_Phonepay\data\aggregated\transaction\country\india\state'
t_states = os.listdir(t_path) # NAMES OF ALL DIRECTORIES IN STATES (36 STATES)

for i in t_states:                     # ITERATE ALL STATES
    #print(i)
    p=t_s+'\\'+i                       # PICK ONE STATE PATH
    states_year=os.listdir(p)          # PICK 2018 TO 2022 DIRECTORIES IN ONE STATE
    for j in states_year:              # ITERATE YEARS 2018 TO 2022
        #print(j)
        pt=p+'\\'+j                    # PICK ONE YEAR PATH
        f=[]
        for (dirpath, dirnames, filenames) in walk(pt):
            f.extend(filenames)        # PICK ALL THE QFILES IN SELECTED YEAR 
            break
        for k in f:                    # ITERATE THROUGH QFILES 1.JSON TO 4.JSON
            fp=pt+'\\'+k               # PICK ONE QFILE PATH
            fn=Path(fp).stem           # NOTE DOWN QUARTER
            #print(i,j,fn)
            Aggregated_Transaction_Table_fun(i,j,fn,fp) # CALL FUNCTION WITH STATE,YEAR,QFILE,QUARTER
            #print(fp)
